services:
  app:
    image: fireflyiii/core:latest
    restart: unless-stopped
    volumes:
      - firefly_iii_upload:/var/www/html/storage/upload
    env_file:
      - .env
    ports:
      - 8081:8080
    depends_on:
      db:
        condition: service_healthy
    networks:
      - firefly
    environment:
      - TZ=Europe/Kyiv
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      start_period: 60s
      interval: 15s
      timeout: 10s
      retries: 3

  db:
    image: mariadb:lts
    restart: unless-stopped
    env_file:
      - .db.env
    volumes:
      - firefly_iii_db:/var/lib/mysql
    networks:
      - firefly
    environment:
      - TZ=Europe/Kyiv
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 30s
      interval: 10s
      timeout: 5s
      retries: 3

networks:
  firefly:
    external: true


volumes:
  firefly_iii_upload:
  firefly_iii_db:
